### ISSUE TITLE
Randomize starting point

### ISSUE THREAD

**Issue by cmkumar87** [ZackAkil/deep-tic-tac-toe#1]
please randomise starting point for AI . Otherwise we have the same game over and over again.

**Comment by ZackAkil** [comment]
Thanks for your suggesting, I'm working on a new model now that will allow the user to go first so that there is more variation in games.

**Comment by ZackAkil** [comment]
Added that new model that can let you go first sometimes to make the start of the game more varied. Although because the model deterministic you may still find some games repetitive if you play the exact same moves.
